### ISSUE TITLE
启动器识别mod文件中文名称有问题

### ISSUE THREAD

**Issue by leesings** [shabbywu/awesome-battle-brothers#1]
![image](https://github.com/shabbywu/awesome-battle-brothers/assets/43227866/eb313bd2-00fa-4d04-a3ba-915b344488ef)

![image](https://github.com/shabbywu/awesome-battle-brothers/assets/43227866/acd94bc6-e4ad-457b-836f-d534e5fa137d)

**Comment by shabbywu** [comment]
编码问题，马上修

**Comment by shabbywu** [comment]
修了一下，扫个病毒就上传

**Comment by leesings** [comment]
![image](https://github.com/shabbywu/awesome-battle-brothers/assets/43227866/f846faf5-e038-4e3c-ad41-fc6c4876d481)

![image](https://github.com/shabbywu/awesome-battle-brothers/assets/43227866/f113682e-cd3f-4744-a05c-02b3c2703859)

![image](https://github.com/shabbywu/awesome-battle-brothers/assets/43227866/3b85edc8-ce23-4c82-b339-631fa92d9529)

**Comment by leesings** [comment]
还是不行

**Comment by shabbywu** [comment]
最近在搬家，很多事情弄。
---
方便的话把你的 Mod 压缩成附件上传上来，我看下能不能复现。
另外确认下 Windows 的一个配置，你当前应该是处于未勾上的状态？试试看勾上去能不能运行（理论上可以）
![image](https://github.com/shabbywu/awesome-battle-brothers/assets/5237578/21e7591b-cc4a-4e09-b400-fba84b8a8d0e)

**Comment by shabbywu** [comment]
已移除该测试特性。
