### ISSUE TITLE
【BUG】GOG启动器错误

### ISSUE THREAD

**Issue by qq913013965** [shabbywu/awesome-battle-brothers#3]
使用GOG启动游戏显示没有Galaxy.dll文件，之前启动一切正常，最近才出现这个问题
![QQ图片20240721153132](https://github.com/user-attachments/assets/9a4f4b2f-8553-4634-ad2a-f81456cc94b9)

**Comment by shabbywu** [comment]
steam 版的游戏，得用 steam 的启动器...
